services:
  discord:
    build: ./
    # image: ghcr.io/taichikuji/sakamoto
    restart: unless-stopped
    mem_limit: 512m
    # Matching the memory limit disables container swap.
    memswap_limit: 512m
    container_name: sakamoto
    environment:
      - TOKEN=${TOKEN}
      - STEAM_TOKEN=${STEAM_TOKEN}
    volumes:
      - sakamoto_db:/usr/src/app/data
    # Label for updater to detect the service to update
    # labels:
    #   - "com.taichikuji.sakamoto.enable=true"

  # Uncomment the following section to enable automatic updates on sakamoto
  # updater:
  #   build: ./updater
  #   container_name: sakamoto-updater
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - .:/workspace:ro,z
  #   environment:
  #     - CRON_SCHEDULE=${CRON_SCHEDULE:-0 0 * * *}

volumes:
  sakamoto_db:
